version: "3.8"

services:
  db:
    env_file:
      - ./back/.env.staging
    volumes:
      # - ./data:/var/lib/postgresql/data
      - /home/bbo/composite/postgres-data:/var/lib/postgresql/data

  cache:
    volumes:
      - /home/bbo/composite/cache:/data

  traefik:
    container_name: composite_gateway
    image: traefik:latest
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # The HTTP port
      - "80:80"

  api:
    image: boursbenjamin/composite-back:0.3.3
    env_file:
      - ./back/.env.staging
    labels:
      - "traefik.http.routers.api.rule=Host(`staging.api.compositethegame.com`)"
      - traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=http://staging.compositethegame.com

  front:
    image: boursbenjamin/composite-front:0.3.5
    depends_on:
      - db
    env_file:
      - ./front/.env.staging
    labels:
      - "traefik.http.routers.front.rule=Host(`staging.compositethegame.com`)"

  api_dev:
    image: boursbenjamin/composite-back:latest
    networks:
      - main
      - database
    env_file:
      - ./back/.env.staging
    labels:
      - traefik.enable=true
      - "traefik.http.routers.api_dev.rule=Host(`dev.api.compositethegame.com`)"
      - traefik.docker.network=main
      - traefik.http.services.api_dev.loadbalancer.server.port=3002
      - traefik.http.services.api_dev.loadBalancer.sticky.cookie.name=server_id
      - traefik.http.services.api_dev.loadBalancer.sticky.cookie.httpOnly=true
      - traefik.http.middlewares.api_dev_middleware.headers.accesscontrolalloworiginlist=http://dev.compositethegame.com
      - traefik.http.middlewares.api_dev_middleware.headers.accessControlAllowCredentials=true
      - traefik.http.routers.api_dev.middlewares=api_dev_middleware

  front_dev:
    image: boursbenjamin/composite-front:latest
    networks:
      - main
    env_file:
      - ./front/.env.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front_dev.rule=Host(`dev.compositethegame.com`)"
      - traefik.http.services.front_dev.loadbalancer.server.port=3000
