name: Install and build front

# on: [pull_request, workflow_dispatch]
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'front/**'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_STAGE: development
      NEXT_PUBLIC_BACKEND_URL: http://api.localhost
      NEXT_PUBLIC_URL: http://front.localhost
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: npm list -w back

    - name: Install dependencies
      run: npm install -w packages -w front

    - name: Build packages
      run: npm run build -w packages

    - name: Build the project
      run: npm run build -w front
