name: Push frontend image

on:
  workflow_dispatch:

jobs:
  push_image:
    runs-on: ubuntu-latest
    environment: staging

    env:
      NEXT_PUBLIC_STAGE: staging
      NEXT_PUBLIC_BACKEND_URL: http://staging.api.compositethegame.com
      NEXT_PUBLIC_URL: http://staging.compositethegame.com
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "18.13"

    - name: Get version
      id: package
      run: echo "::set-output name=version::$(node -p "require('./front/package.json').version")"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./front/Dockerfile.front
        target: staging
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/composite-front:${{ steps.package.outputs.version }},
          ${{ secrets.DOCKERHUB_USERNAME }}/composite-front:latest
        build-args: |
          NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          NEXT_PUBLIC_STAGE=staging
          NEXT_PUBLIC_BACKEND_URL=http://staging.api.compositethegame.com
          NEXT_PUBLIC_URL=http://staging.compositethegame.com
